ProductPanelRole: ["1200120995839742042"]

panels:
  DrakoBot:
    title: "Drako Bot - Download Panel"
    description:
      - "**Please choose a product to download:**"
      - ""
      - "📦 **Standard Release** - **$9.99**"
      - "[Purchase here](https://builtbybit.com/resources/drako-bot-multi-purpose-discord-bot.22266/?ref=discover)"
      - ""
      - "🧊 **Full Source** - **$52.99**"
      - "[Purchase here](https://builtbybit.com/resources/drako-bot-multi-purpose-discord-bot.22266/?ref=discover)"
      - ""
      - "Need assistance or more info? Contact our support team."
    Footer: "Powered by Drako Development"
    ThumbnailURL: "https://i.imgur.com/aSUtzbN.png"
    AuthorURL: ""
    AuthorName: ""
    FooterURL: "https://images-ext-1.discordapp.net/external/sRbhw85jURn7_EaCyTDHWOfmTKxvL1dklZw7TiNTOZQ/https/i.imgur.com/HDdh7Me.png?format=webp&quality=lossless&width=640&height=640"
    embedColor: "#315FFF"
    useButtons: true
    products:
      - name: "Standard"
        emoji: "<:Developer:1208223076408361010>"
        description: "Standard Download"
        roleId: "1200120995839742042"
        zipFilePath: "../../products/DrakoBot/Standard" # This example directory is in the base directory of the bot, where config.yml is. Make the products folder and so on.
        buttonLabel: "Standard Download"
        buttonColor: "SECONDARY"
      - name: "Full Source"
        emoji: "<:Developer:1208223076408361010>"
        description: "Full Source Download"
        roleId: "1200120995839742042"
        zipFilePath: "../../products/DrakoBot/FullSource"
        buttonLabel: "Full Source Download"
        buttonColor: "SECONDARY"
    cooldownDuration: 3600
    
    
  Addons:
    title: "💰 Drako Bot - Addons"
    description:
      - "**Please choose a product to download:**"
      - ""
      - "💾 **Product Panel** - **$5.00**"
      - "<#1206671824780525638>"
      - ""
      - "Need assistance or more info? Contact our support team."
    Footer: "Powered by Drako Development"
    ThumbnailURL: "https://i.imgur.com/aSUtzbN.png"
    AuthorURL: ""
    AuthorName: ""
    FooterURL: "https://images-ext-1.discordapp.net/external/sRbhw85jURn7_EaCyTDHWOfmTKxvL1dklZw7TiNTOZQ/https/i.imgur.com/HDdh7Me.png?format=webp&quality=lossless&width=640&height=640"
    embedColor: "#315FFF"
    useButtons: true
    products:
      - name: "Product Panel"
        emoji: "<:Developer:1208223076408361010>"
        description: "Product Panel"
        roleId: "1200120995839742042"
        zipFilePath: "../../products/Addons/ProductPanel"
        buttonLabel: "Product Panel"
        buttonColor: "SECONDARY"
      - name: "Sticky Messages"
        emoji: "<:Developer:1208223076408361010>"
        description: "Sticky Messages"
        roleId: "1200120995839742042"
        zipFilePath: "../../products/Addons/StickyMessages"
        buttonLabel: "Sticky Messages"
        buttonColor: "SECONDARY"
    cooldownDuration: 3600

messages:
  panelNotFound: "Panel configuration for \"%s\" not found."
  panelPosted: "Panel Posted."
  failedToDisplayPanel: "Failed to display panel."
  productNotFound: "Product not found."
  noRequiredRole: "You do not have the required role to download this product."
  cooldownMessage: "You can download the product again <t:%s:R>. (just wait)"
  fileSizeExceeds: "Sorry, the file size exceeds the current limit for this server's boost level. The maximum allowed is %s MB."
  downloadReady: "Here is your download:"
  downloadError: "Error preparing the download, please try again later."
  preparingDownload: "Preparing your download..."

selectMenu:
  placeholder: "Choose a product"